export type RootStackParamList = {
  Mine: { userId: number };
  Main: undefined;
  IDPhoto: undefined;
  KnowledgePlanet: undefined;
  LuckDraw: undefined;
  Watermelon: undefined;
  StaticWebview: undefined;
  NativeModule: undefined;
  Index: undefined;
  Login: undefined;
  MainStack: undefined;
  Splash: undefined;
  Notice: undefined;
  ClubDetail: { clubId: number; clubName: string };
  ClubPosts: { clubId: number; clubName: string };
  ClubVote: { clubId: number; clubName: string };
  ClubWritePosts: { clubId: number; clubName: string };
  ClubPostsDetail: { clubId: number; postId: number };
};
